boundlessgeo/exchange

dev/settings.py
Enabling the REST uploader in dev/settings.py to prevent users from uploading unsupported file types.
=> Change importer from geonode.importer to geonode.rest

cf/init_db.sh, dev/bootstrap.sh, requirements.txt
Updates Exchange to use the latest GeoNode master, which means a bump to Django 1.8 (among other things). `django-tastypie` has also been unpinned from our own deps to let us pull the appropriate version (matched to Django version) via GeoNode.
Also updates Exchange's use of `syncdb` to use `migrate` instead, as `syncdb` has been deprecated and is going away completely in Django 1.9.
Fair warning, I'm unfamiliar with everything else that changed with the move from our previous, much-older pinned GeoNode version to GeoNode master - so I'm not sure if there's a more complete QA process to be run here other than "works on my box".
**storytime:**
There is an issue with interdependent migrations. (related: [this](https://lists.osgeo.org/pipermail/geonode-devel/2016-February/000780.html) ML …
=> Upgrade to master GeoNode

dev/CHANGELOG.md
Ref: https://issues.boundlessgeo.com:8443/browse/NODE-158
Added a changelog to track significant changes; documented migration steps needed to go from Django 1.6 --> Django 1.8.x
=> add change doc with new migration steps

exchange/settings/default.py
The catalog list from the default config gets passed to MapLoom as a string that needs to be parsed using JSON.parse(), which requires that all JSON keys be wrapped in double quotes.
=> Replace single with double quotes in config catalog list

requirements.txt
This patch avoids some warning messages which are probably harmless.
Since I run out of RAM on my little laptop, I need help testing that everything still builds correctly, or alternatively I can test this in a week.
=> fix egg fragments generating pip warnings

setup.py
Right now if you `pip install ./exchange` (or the like) the resulting install will not include subpackages such as exchange.settings in the copy installed in site-packages, because the relevant distutils function does not search subdirectories. This is at least one barrier to using the package in-place from a pip install, requiring it to be used from a copy of the source tree.
=> use setuptools to find subpackages

exchange/static/css/site_base.css, exchange/templates/site_index.html
[NODE-214](https://issues.boundlessgeo.com:8443/browse/NODE-214)
No need to override geonode's styles here just to change alignment on one icon ("Layers" on index). The old override was messing with icon-to-text alignment across the site.
=> Fix category icon alignment

exchange/templates/base.html, exchange/templates/site_index.html
resources redirect automatically to the first page of query results;
this "breaks" user expectations of the back button (requiring two clicks
to back out through the redirect & return to previous page).
REF: https://issues.boundlessgeo.com:8443/browse/NODE-215 & https://issues.boundlessgeo.com:8443/browse/NODE-216
=> link directly to first page of query results to skip redirect

exchange/settings/default.py
with only a first argument, os.path.join(x) == x.
[See the source in posixpath.py](https://hg.python.org/cpython/file/2.7/Lib/posixpath.py#l61) if you need to prove this to yourself
=> remove redundant call to os.path.join

exchange/settings/default.py
=> Uploaded resources should be private and not downloadable by default

exchange/settings/default.py
Per https://issues.boundlessgeo.com:8443/browse/NODE-310.
Seems to work for me, but I'm not sure what all this affects, so this needs testing/inspection from someone more familiar with the issue.
=> Use https:// in Gravatar URLs generated through django-avatar

exchange/urls.py
The way these lines have been is pretty confusing because it drags in geonode.urls.urlpatterns (which makes things confusing when we want to bring in urlpatterns from other places) and then it modifies it in the current scope. You need a very solid understanding of Python to understand how this worked.
I also want to get rid of `import *` wherever possible, it never should have existed in Python, and this is a relatively easy instance to get rid of
This is part of prep for a rebased version of Sara's django-osgeo-importer PR from June
=> tidy import of urls from geonode

Dockerfile
Registry requires libmemcached-devel to be installed.
=> Add libmemcached-devel to docker setup

dev/bootstrap.sh, docker/geoserver/Dockerfile
Update the Vagrant bootstrap.sh and Docker files to use the GeoServer 2.9 image that contains the latest released GeoGig plugin version 1.0-RC3
=> Update GeoServer WAR for Vagrant and Docker to use 2.9 image with GGig 1.0-RC3 plugin

Dockerfile, docker/home/.bashrc
The aliases are left intact in the Vagrant config, which is not touched.
I originally included these for continuity with the vagrant config, but in the docker config I don't think these are needed at all and are only going to cause confusion.
=> remove shell aliases in docker config

Vagrantfile
This change has been floating around as lore for too long.
Example of the problem follows:
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/centos-6.7' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
default: Adapter 1: nat
default: Adapter 2: hostonly
==> default: Forwarding ports...
default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
default: SSH address: 127.0.0.1:2222
default: SSH username: vagrant
default: SSH auth method: …
=> Vagrant kludge for '(config.ssh.shell) is invalid'

dev/bootstrap.sh, docker/home/common.sh
There was a reason why initial_data.json was renamed to initial.json:
initial_data is autoloaded every time migrations are run, which was causing
some data to be lost: in thi scase, it would switch to the default template,
when some deploys for clients had another template.
(Django is deprecating that automagic soon anyway, but we didn't want it here.)
However, we do still want to load that data in a new instance, hence
this commit. Just renaming initial_data to initial left new dev instances in
a dumb state (e.g.: ValueError at /account/login/ - The 'logo_image' attribute
has no file associated with it.)
Unfortunately, ./manage.py loaddata some_invalid_fixture_name actually
runs with exit code 0, so the scripts weren't halting as they should have
in order to highlight the problem, but …
=> use initial.json instead of initial_data

docker/home/.bashrc
apparently the removal of .bashrc causes docker exec shells to do the familiar behavior of killing the shell any time a command is issued which exits with an error code.
(btw, set -e might be involved in the behavior we see in the Vagrant environment, but I don't have all day to experiment with it)
=> stub .bashrc so docker exec shells don't exit on every error

dev/bootstrap.sh, docker/home/common.sh
Dan's suggested workaround which will hopefully not break when GeoNode lands a PR to fix migration dependency ordering issues.
Locally working against both vagrant and docker on exchange master.
=> vagrant, docker: extra migrate account for DoesNotExist profile issue

exchange/settings/default.py
This is being changed locally by devs and should be revisited when we can actually leave it enabled after proper testing.
=> revert change to JSON serialization for celery

exchange/static/css/site_base.css
JIRA: https://issues.boundlessgeo.com:8443/browse/NODE-379
Depending on page content (and whether `.page-header` appears on the first `div`), spacing between the nav area and the page content is inconsistent, so things like alerts were not always visible and sometimes were obscured by the navigation.
This fix applies consistent padding under the nav on `#wrap` so that no content can be hidden by the navigation. It also removes margin that was applied to `.page-header` so that we're not getting a double height of spacing below alerts and other UI elements that appear before `.page-header`s. Screen shots below confirm that the change in appearance to pages using `.page-header` is minimal.
=> Change wrapper and page title margin so content is always visible.

exchange/templates/layers/metadata_detail.html, exchange/templates/maps/metadata_detail.html
When values like email and location were empty strings (possibly because they have string type in the database), the template was rendering <dd></dd>, which meant that all the other <dd> elements were pushing up the page, along with the following span.subtitle.
Why fix this at the Django template level?
1. It doesn't seem useful, and will introduce other complications, to ensure the database has NULLs or that we intervene at the Python level (before template rendering) to translate null strings into None.
2. We probably either want to delete both dt and dd, or to explicitly indicate to user that there is no value. So if in the future there is a solution which doesn't require adding presentation-only classes to dd tags, that could be worth taking, but we still need the template-level fix.
=> avoid empty dd tags in metadata detail templates

requirements.txt
The main goal of this version is to support a CSW-T workflow, it has been tested with the RIO Foundation Layers from NGA while maintaining the ability to harvest records.
Version 0.3.11
- Elasticsearch 1.7 compatibility.
- CSW-T Insert support with custom <registry> tags.
- Custom <registry> tags available in MapLoom UI.
- Full screen MapLoom Registry modal.
- Adaptive pagination based on available height.
- Fixed MapProxy issues with WMS servers. workspace:name is now sent as layer name instead of name.
- Fixed map display issues on hover for ArcGIS layers.
- is_monitored is set to False on services uploaded via CSW-T.
- Added users, admins and developers documentation.
- More robust parsing of ArcGIS services url.
- Switched to q.param and a.param instead of a_param and q_param for …
=> [1.0.2] Switch to django-registry==0.3.11 and pycsw==2.0.1

requirements.txt
Of the 1.0.2 registry updates this will be the only change to master. In the future there should not be any additional updates to MapLoom in regards to registry, since it now pulls data via an api. 
The reason why this will be the only change is that in the next release we will be adding a PR soon to remove registry from exchange and install it separetly in the rpm. A separate branch v1.0.2 has been created that includes the new registry changes. This maploom version has been tested in client environment.
=> MapLoom update to use swagger api for registry + v1.0.2 updates

docker/nginx/exchange.conf
When using the docker dev environment, we need to be able to upload files to Exchange that are bigger than the rather small default size limit set by the nginx that is proxying to Exchange.
This is an internal need that does not have a specific JIRA story, but it arose while trying to test NODE-362. Also, there have been some recent mentions of Exchange's behavior with larger datasets in connection to GeoGig. So this issue will come up and we might as well have this done in advance since it's so trivial
=> make dev nginx accept absurdly large uploads for testing

exchange/core/context_processors.py
This is for consumption by templates e.g. from osgeo_importer.
=> expose INSTALLED_APPS from resource_variables

docker/home/common.sh, docker/home/exchange.sh
The recent PR removing files like exchange/core/admin.py may cause any remaining *.pyc files still present in the Exchange working tree to be imported (via mounts) in the docker container, causing mayhem. Same may happen in future changes as well. This automates the cleanup to prevent that.
Wouldn't be an issue except for the use of mounts, which is hard to do away with
=> remove *.pyc preventively during container boot

dev/bootstrap.sh, docker/home/common.sh, exchange/core/fixtures/base_resources.json, requirements.txt
bump version to 2.5.5 (https://github.com/GeoNode/geonode/pull/2692/commits/4227d8dc687c331527cbfa5f9550f974dace4b5c) addressed an issue with certain files not be packaged up.
Issue with topic categories not being loaded. We must have overlooked this, because data will still load and not require the user to first selecta  topic category. If the user does go to the '/layers/{layer name}/metadata page they are not able to save any changes due to the category list not displaying. Steps have been added to load data for both initial (admin and test default accounts) and initial_data (topic categories - https://github.com/GeoNode/geonode/blob/master/geonode/base/fixtures/initial_data.json)
=> update GeoNode to include pycsw security fix.

exchange/__init__.py, requirements.txt, setup.py
- Updated version to 1.1.0c1
- Removed gunicorn as a dependency from exchange
- set versions for django-exchange-maploom and django-exchange-themes
- removed TODO section from requirements.txt
- added set versions for 1.1.0rc1 release in the install_requires section of setup.py
=> Exchange release 1.1.0rc1

exchange/__init__.py
- when importing exchange.settings the init was causing an error when trying to `from celery_app import app as celery_app`, since the settings had not been set for django.conf.
=> Issue when using exchange as a package

exchange/settings/default.py
In django-osgeo-importer, default handlers have been moved out of code and into project-level settings to (ultimately) support geoserver-independent geonode layer imports.
_Reference https://github.com/boundlessgeo/django-osgeo-importer/pull/43 for details_
=> default osgeo-importer handlers now in settings

requirements.txt
Reference: https://github.com/boundlessgeo/exchange/pull/104, https://github.com/GeoNode/geonode/issues/2700
This is just an ugly, **temporary** fix to get Travis CI up & running again. Should be removed once Travis is modified to pull deps from GeoNode's requirements.txt
=> TEMPORARY shim to resolve celery issue

docker/home/common.sh
Use dependency versions explicitly pinned in GeoNode's requirements.txt for development. See https://github.com/GeoNode/geonode/issues/2700 for related issue
=> Install GeoNode deps from requirements for development

.travis.yml
The Dec 1 update to Travis CI broke postgis with postgresql 9.5. See https://travis-ci.org/boundlessgeo/exchange/builds/181781483#L435.
Some related issues & discussion:
https://github.com/travis-ci/travis-ci/issues/5509
https://github.com/travis-ci/travis-ci/issues/4264
https://github.com/travis-ci/travis-ci/issues/6972
This is one possible solution. We'll see if it works.
~*DO NOT MERGE* - testing Travis.~ Yep, this works. Safe to merge once CI completes.
=> Fixing Postgres 9.5 + PostGIS on Travis CI

docker/README.rst
Reference https://github.com/boundlessgeo/exchange/pull/106 -- this change added a dependency on a local MapLoom build, including `MapLoom/build` directory. Updating docs to include MapLoom clone/build instructions.
=> Dev readme update

exchange/settings/default.py
cleaned up the settings file to allow for environment variables. I did leave out osgeo_importer, to prevent any accidental deployments. The default setting for exchange is to use postgres and postgis for django, geoserver and geogig. There is no longer an option for sqlite, since we do not use it and if the settings are not properly configured it will display that in the logs rather than just creating a sqlite db. I did add the option for classification, needed for dod customers and registration / email server needed for the trial and demo server.
=> configure settings file to support all env variables

docker/geoserver/Dockerfile
I found that uploading GeoGig layers was not working because there were
missing spaital libraries.  This may only fundamentally apply to SpatialLite databases,
however, there were errors in the geoserver log indicating that it has been looking
for GEOS and PROJ4 and not finding those libraries even without accessing a
SpatialLite database.
=> Fixed missing spatial library warnings.

exchange/core/context_processors.py, exchange/settings/default.py, exchange/templates/people/profile_detail.html, exchange/urls.py
This is a redo of PR #103 which should prevent the user from being able to use registry services by default in Exchange. They can be enabled by setting the `REGISTRY` variable to `True`.
Although it is not visible, this same variable is present in MapLoom. By setting it to False, it should prevent the error state from being reachable in MapLoom as well.
Therefore:
- Setting the REGISTRY variable in Exchange's settings to False prevents a potential error state in MapLoom
- We can also leverage the REGISTRY settings variable to block the endpoint in Exchange, so the user cannot use functionality that they won't be able to access in MapLoom anyway
=> Disabling registry services by default

dev/bootstrap.sh, docker/geoserver/Dockerfile, docker/home/common.sh, docker/home/docker_oauth_apps.json, exchange/settings/default.py, exchange/themes/migrations/0003_auto_20170104_0910.py
Automated the configuration for [geoserver_geonode_security](http://docs.geonode.org/en/latest/tutorials/admin/geoserver_geonode_security/index.html) both Docker and Vagrant (RPMS will need adjustment via the spec file)
- added a specific fixture for oauth2_providor (Docker)
- added new additions for login and logout endpoints to `OGC_SERVER` dictionary.  (All deployments)
- added required `AUTH_EXEMPT_URLS` that are required for geoserver oauth extension to communicate to geonode auth api when `LOCKDOWN_GEONODE` is set to True. (All deployments)
- now loads the docker_oauth_apps fixture during the execution of the common.sh (Docker)
- added some sed statements to allow for an automated deployment of geoserver with an oauth config to exchange docker setup. (Docker)
- now loads the default …
=> NODE-634 setup to use new geonode/geoserver oauth2 configuration

requirements.txt
Push django-exchange-maploom to 1.5.14, Geonode to a version the includes OAuth and Geogig fixes, and point dj-database-url back at pypi instead of our fork
=> Version upgrades

exchange/settings/default.py
This adds the ability to specify two new environment variables:
ADDITIONAL_AUTH_EXEMPT_URLS 
ADDITIONAL_APPS
Both or comma delimited strings.
This helps solve an issue with account registration/creation not working.
=> Add ADDITIONAL_AUTH_EXEMPT_URLS and ADDITIONAL_APPS

.travis.yml, Dockerfile, Dockerfile.ci, dev/bootstrap.sh, docker/home/common.sh, docker/home/exchange.sh, docker/home/local_settings.py, docker/home/worker.sh, docker/travis/migrate.sh, docker/travis/run-server.sh, docker/travis/test-geonode.sh
The boundless-vendor-libs has been added to docker and vagrant configuration. The location of the libs are now in `/opt/boundless/vendor/lib`, the files have also been adjusted to add postgresql installed at `/opt/boundless/vendor/{lib,bin}`. The inclusion of the vendor-libs allowed for epel to be removed as a dependency. A settings variable, `GEOS_LIBRARY_PATH`, was added for docker config, since a custom location was used for geos.  
There was a change from having the Dockerfile for exchange install all requirements and then have common.sh upgrade the dependencies by using the upstream requirements. A change recently to upstream was causing issues when installing the dependency for six and paver. The change that has been applied to docker setup is to remove the geonode entry in the …
=> Use boundless-vendor-libs rpm and remove upstream requirements.txt

exchange/templates/base/_resourcebase_snippet.html
The primary cause of this bug was that the message was showing
before Angular had the chance to parse the document.
Adding "ng-hide" to the div's class makes it invisible to the user
while the page was loading, and then "ng-show" is used to remove
the "ng-hide" class when applicable. But as that is done by the
Angular parser, the content is ready when the div is shown.
Refers to NODE-583
=> Fly-by 'Error' Messages in resource lists.

requirements.txt
After version 0.9.0 waitress began stripping HTTP headers that contain
an '_' character. This is due to a potential security vulnerablity that
can arise from underscore/dash conflation.
GVS currently uses "OAM_REMOTE_USER" as a header in order to provide
authentication credentials to other services from their GeoAxis server.
This means that waitress needs to allow for that value until we determine
a better way forward with GVS.
This fix is meant to be a TEMPORARY solution so that GVS's testing team
can begin looking over their Exchgange deploy.
See https://github.com/Pylons/waitress/pull/80 and
https://www.djangoproject.com/weblog/2015/jan/13/security/ for more info
about the waitress security issue.
=> Revert waitress to previous version

requirements.txt
http://docs.celeryproject.org/en/3.1/configuration.html#redis-backend-settings
#144
=> NODE-703 Add celery[redis] bundle for redis broker support for celery.

exchange/templates/layers/layer_detail.html
The buttons are hidden when the preview viewer is react, the buttons were set to geoxt viewer only (geoext viewer is the old ol2 viewer).  An issue has been created in geonode-client [https://github.com/GeoNode/geonode-client/issues/145]. Modified the template to at least expose the option to manage the available styles, until the feature can be added to the ol3 react viewer.
=> NODE-700 Manage and Edit style options are missing from Edit Data

exchange/views.py
Fixes issue with category filters in unified search. For some reason Elastic Search is truncating categories to 13 characters, so this truncates the query to match. Should still figure out what is causing this.
=> fix to category filters

exchange/settings/default.py
Exposes two environment variables **_OSGEO_IMPORTER_ENABLED_** and **_GEONODE_CLIENT_ENABLED_** that make it easier to disable either if needed
=> Make osgeo-importer and geonode client optional and enabled by default

exchange/settings/default.py, requirements.txt
- geonode.rest is now the default uploader
- using a fork of geonode
- use GEOSERVER_LOCAL_URL when possible or if set by os.environ
=> changes for 1.2.0

exchange/core/context_processors.py
Adds support for a 'preview layer' configuration that is
passed onto maploom.
Setting MAP_PREVIEW_LAYER will be pushed to the templates so that it can be rendered in the map:
```
MAP_PREVIEW_LAYER = {
"source": {"ptype": "gxp_arcrestsource",
"url": "https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer/",
"proj": "EPSG:4326"},
"args": ["Worldmap",
"https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer/",
{"layers": "basic"}],
}
```
=> Allow for passing a preview configuration.

exchange/templates/layers/layer_detail.html
The createMapThumbnail function is in thumbnail.js which
was not being included by the geonode-client app.  The exchange
template has been changed to include the necesary javascript file
before loading the Geonode-client package map.
=> Fixed missing createMapThumbnail function

exchange/settings/default.py
The previous check was checking if the value was not null, which caused an issue when the exchange-settings.sh was set to False.
=> adjusting settings check for WGS84

exchange/urls.py, exchange/views.py
it seems as though bumping ES versions was creating issues with haystack search on dev.exchange. this makes all searches run through the ES_UNIFIED SEARCH when enabled
addresses NODE-752
=> make documents and layers search use unified search when enabled

exchange/settings/default.py
Using ```geonode.importer``` instead of ```geonode.rest``` to support importing into Geogig
=> geonode.rest -> geonode.importer for Geogig imports

exchange/settings/default.py, exchange/themes/templates/base.html, exchange/urls.py, requirements.txt
This replaces the deprecated ```python-social-auth``` to ```social-auth-app-django```.
Also moved the ```social_django``` app to only be included if social login is enabled
This was tested on https://dev.exchange.boundlessps.com
**Known issues:**
- On initial login from Google the user will be pointed to ```/accounts/profile/```
- Authentication to Goggle backend will fail because  ```certifi``` (even the latest version) has an old cacerts.
```certifi```will have to be uninstalled
=> Social login V2

docker-compose-unified-search.yml, docker/registry/Dockerfile, docker/registry/registry-settings.sh, docker/registry/run.sh, docker/registry/setupdb.sh
The previous version of the registry docker setup
used the registry RPM to setup the registry environment. This version
of the docker file properly sets up the environment to use a clone
of the repository.  If the developer wishes then they can setup
a "local mount" of the repository and develop in a similar manner
to how exchange, maploom, and geonode are currently configured.
=> Added Support for Local Registry Development.

.coveralls.yml, .travis.yml, README.rst, docker/travis/Dockerfile.ci, docker/travis/coveralls.sh, docker/travis/pytests.sh
adjusted coverage reporting to use codecov.io not coveralls.io, codecov has a bash command that allows publishing the report within the container. Updated the badge in the readme.
=> codecov.io integration

exchange/settings/default.py
The value that Geoaxis returns as its header for
authentication is customizable and can vary from
instance to instance. As a result the user of
Exchange should be able to customize the value
Exchange looks for to match their flavor of
Geoaxis.
=> Allow setting of GEOAXIS_HEADER via ENV VARS

exchange/templates/base/_resourcebase_snippet.html
This is a little ugly but because this template is reused in multiple places and the dataValue variable is reused in those places to mean completely different things, it's placing an ad hoc if check to see if we should use dataValue as part of the message to display or not.
Alternatively, can just use the word "content" or something to have a generic static message instead.
=> Fixed incorrect empty search text messages for maps/layers

exchange/settings/default.py
This is required by social auth to set the correct ```redirect_uri```, and also solves possible issues with ```/api/categories``` and ```api/owners``` redirecting to HTTP when using HTTPS
=> Set X_FORWARDED_PROTO and X_FORWARDED_HOST headers in Django

exchange/tasks.py
@davisc reported an issue (NODE-757) with non-XML 200* responses causing CSW record insertion to fail. This addresses that, while also adding a delayed retry on failed record insertion tasks.
*_non-200 responses are [already handled](https://github.com/boundlessgeo/exchange/blob/master/exchange/tasks.py#L90), but unfortunately Registry returns non-XML errors with a 200 status code_
=> CSW Record form: handle non-XML 200 responses, retry on errors

exchange/static/css/site_base.css, exchange/static/js/search/workspace.html, exchange/templates/base/_resourcebase_snippet.html, exchange/templates/search/search.html
In the new search screen it was possible to add registry layers and maps to the "Workspace"/cart.  These things are broken functionality in the current application.  This PR prevents the user from performing those actions. A bit of detail:
1. Fixes from CSS with the cart items when the title gets too long.
2. Filter out "add" buttons from items which are not layers.
3. Ensure all filters and the "Create a Map" button can be displayed at the same time.
Depends on : 
- https://github.com/boundlessgeo/geonode/pull/39
Screenshot:
=> "Workspace" addition bugs

exchange/themes/templates/index.html
Inline CSS does not need to wait for CSS or Angular to load to
hide the contents of the feature datasets.  Only once the layer
list has loaded will the list display.
=> Added additional CSS to prevent fly-by message.

exchange/templates/account/login.html, exchange/themes/static/theme/css/site_base.css
This PR fixes:
- the google redirect error by supplying the `next` parameter
- applies styling to the social buttons.
- consistent use of `Log In` instead of `Log in` or `Sign in`
=> Apply Styling to the Social Buttons

exchange/core/context_processors.py, exchange/settings/default.py, exchange/templates/account/login.html, exchange/themes/static/theme/css/site_base.css, exchange/themes/templates/base.html
This PR does the following:
- Adds a consent page to the login workflow
- Consent page text is configurable
- Consent page supports two authentication providers 1) Exchange local and 2) GeoAxis
- Hides header nav when LOCKDOWN is enabled and displays it once the user has authenticated
- Switched text Sign in to Log In to be consistent with the rest of the application
**EXCHANGE_LOCKDOWN mode enabled and user not authenticated**
**EXCHANGE_LOCKDOWN enabled, LOGIN_WARNING enabled, GEOAXIS enabled and user not authenticated**
**EXCHANGE_LOCKDOWN enabled, LOGIN_WARNING enabled, GEOAXIS DISABLED and user not authenticated** Defaults to username password authentication
=> Consent Banner for Exchange

exchange/tests/test_get_version.py, exchange/tests/themes_test.py, exchange/tests/upload_test.py, exchange/tests/views_test.py, exchange/views.py
This is some work to generally increase the test coverage across a number of modules.
1. The unified search view was refactored slightly to support better functional testing.
2. Additional tests to increase coverage based on the above.
3. Added a way to test the get_version function.
4. New tests for the theme template changes exchange uses.
=> Increasing Test Coverage

exchange/tests/fileservice_test.py
Removed the username/password assumptions from file service test.
=> Moved to self.login() instead of default passwords.

exchange/templates/base/_resourcebase_snippet.html
The template now checks to see if the category is "[]" and when it is, it is displayed as "" instead, otherwise the category is display as before.
=> Displays category as empty instead of "[]"

exchange/themes/templates/site_base.html
With the latest change to the Exchange core style
the GeoInt logo becomes distorted and doesn't fit
properly on the nav bar like it should. This change
is meant to restyle the logo so it sits correctly.
=> Update site_base.html to correctly size GEOINT Logo

exchange/core/context_processors.py, exchange/settings/default.py, exchange/tests/core_test.py
Requires https://github.com/boundlessgeo/MapLoom/pull/83 for GeoQuery search to be enabled (default settings for OSM will continue to function correctly, so it is safe to merge)
=> Add context and settings variables to handle GeoQuery search

docker-compose-unified-search.yml, exchange/tests/upload_test.py
1. Added REGISTRY_LOCAL_URL configuration.  An earlier commit
changed REGISTRYURL to REGISTRY_LOCAL_URL.
2. Added a skip-decorator to the upload tests for when
elastic search is not enabled in the environment.
=> Clear Uploader Test Failures in Travis

exchange/thumbnails/static/geonode/js/utils/thumbnail.js
Previous verison of the thumbnail sampler used
clipping. The new version uses scaling to capture
the entire map view.
=> Updated thumbnail to use scale and not clip.

exchange/tests/thumbnail_test.py, exchange/thumbnails/models.py, exchange/thumbnails/views.py
A slight difference between how the ORM expected the compound primary key to work and how .save was actually working has been causing some bugs when saving thumbnails.  This fixes that situation and centralizes the logic into thumbnails.models.save_thumbnail.
A new test has been added to prove that this actually fixes the problem as well.
=> Fix for Primary Key Bug with Thumbnails

exchange/auth/backends/geoaxis.py, exchange/settings/default.py, exchange/templates/account/login.html
This PR applies a fix to an issue found in the latest version of Exchange where the incorrect Scope was sent to GeoAxis causing the request to fail. The Scope can now be configured via settings.
=> Removed deprecated setting and allow the scope to be configurable.

exchange/auth/backends/geoaxis.py, exchange/settings/default.py
This PR removes the hard-coded client key and forces https for redirect handling. Without this change, installs configured for https will fail on the redirect back to the application because the application will send http://<site_url> as the redirect. Lastly this PR allows the social_django app to be installed by default so that the models can be created during Exchange install.
=> Configure the key and secret

dev/settings.sh, dev/supervisord.conf, exchange/settings/default.py, exchange/urls.py, requirements.txt
The configuration provided is an example configuration of NearSight inside of Exchange.  
Adding `NEARSIGHT` to the environment will add the nearsight URLs.
Then migrations will need to be ran.  
Lastly in order to work properly a directory needs to be provided for `NEARSIGHT_UPLOAD` with permissions given to the django server to read and write to the directory.
=> added nearsight configuration

exchange/core/migrations/0001_initial.py, exchange/core/migrations/0002_lengthen_csw_source.py, exchange/core/models.py, exchange/tests/celery_test.py
1. Adds 0001_initial.py migration file which describes the models.
This was needed because Django needs *something* to start from
in migrations to define the data.
2. The 0002 migration actually lengthens the URL field.
3. The model is updated to reflect the lengthened field.
Running these requires some trickery!!!
Instead of just `migrate` we need `migrate --fake-initial` in order for this to migrate properly! The initial models were not managed by migrate; so "faking" it is requires on the initial migration intake.
```
python migrate.py migrate --fake-initial
```
=> Migration script to lengthen CSW Record URLs.

exchange/audit/migrations/0002_username.py, exchange/audit/models.py
This change was done so users are not prompted to set a default when migrating.
Currently users are prompted when upgrading with the following:
```
System check identified some issues:
You are trying to change the nullable field 'username' on auditevent to non-nullable without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
1) Provide a one-off default now (will be set on all existing rows)
2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL operation to handle NULL values in a previous data migration)
3) Quit, and let me add a default in models.py
Select an option:
```
=> Audit username field can be null

exchange/tests/__init__.py, exchange/tests/csw_perms_test.py, exchange/themes/templates/base.html, exchange/views.py
1. Added a registry link that goes to the "insert_csw" URL.
2. Changed templates to hide Registry, Admin, GeoServer from users without permission to use them.
3. Added supporting tests to verify the above.
Issues
NODE-868
=> Add Registry Link, Lock Down Admin-only Menu Links

exchange/views.py
Adds temporal extent search to the api. To automatically fill the temporal extent on import, this requires PR #274. 
Adds extent__range, extent__lte, and extent__gte parameters to the api. Does not add elements to the UI.
This searches against the range of data such that if any part of the range in the data intersects the given range it will match.
NODE-872
=> add time filtering for dataset extent

exchange/themes/templates/index.html
Featured content thumbnails were missed in the API update.
This fixes that oversight.
=> Fixed Thumbnail URLs to match new API.

exchange/themes/static/theme/css/site_base.css
The form control CSS was preventing the keyword list editor
from expanding properly.  This fixes those layout problems.
=> Added some helpful CSS for keyword list layout.

exchange/themes/templates/index.html
As `detail_url` includes a leading "/", this removes the double "//" created
when defining the src for the thumbnail.
Refs: NODE-915
=> Fix for the feature content thumbnails.

exchange/static/osgeo_importer/importer.js, exchange/static/osgeo_importer/partials/upload.html, exchange/static/osgeo_importer/partials/uploadWizard.html
Refs: NODE-823
1. The layer_name, which is not honoured by the uploader is
now read-only and there is an explanation as to why it is read-only.
2. Dropped the geonode logo from the uploader as a clean-up touch.
3. As the uploader was not allowing for layers to be uploaded twice
without generating an error, the "Create Layer" link is now
substituted out with a "View Layer" link.
4. There is now a surface-level check to tell the user that the
layer they are working with may already have been uploaded.
Some screenshots for posterity:
=> Improvements to uploader to fix layer confusion.

exchange/storyscapes/views.py
Fix the permissions error when saving stories.
=> Check perms on the base resource

exchange/templates/layers/metadata_detail.html
The error shown in NODE-358 was a legitimate OGC Service
error.  It was saying, quite literally, "No request given",
this updates the metadata page to point at the server's GetCapabilities
document.  Useful for a couple of reasons:
1. The GetCapbilities link can be fed to a desktop client to
load the data in them.
2. The GetCapabliites doucment is expressly metadata for the service
available.
=> Have OWS links show the capabilities.

exchange/core/forms.py
In order to provide a better experience to the
end users, it was identified that some of the labels
should be updated to more correctly reflect the
terminology that they (end users) would use or expect
on the CSW input form.
=> Update CSW form to include proper labels

exchange/themes/templates/about.html, exchange/themes/templates/base.html, exchange/urls.py, exchange/views.py
Includes a new About tab for Boundless Exchange. The tab is accessible from the footer similarly to the Documentation page. Additionally, it is accessible in the "About" dropdown menu in the header.
The new view grabs and displays information about the community and sub projects Exchange relies on, including version numbers, contributors from Boundless, the commit hash being used, and so on. The about tab is designed to show what is new with the version of Exchange and the current versions of the dependent projects. Images below.
**NOTE**: The following PR's are required for the Version Dependency section to show versions and commits correctly.
https://github.com/boundlessgeo/geonode/pull/62 [MERGED]
https://github.com/boundlessgeo/django-exchange-maploom/pull/6 [OPEN] …
=> Added about tab with info about Exchange and dependent projects

exchange/themes/templates/base.html, exchange/themes/templates/tracking_footer.html, exchange/themes/templates/tracking_header.html
For certain deploys, it is desireable to include
scripts for tracking and analytics to the Exchange
site. This commit adds tracking_header.html and
tracking_footer.html as the defacto place to put
that scripting.
=> Add place to include tracking scripts when desired

exchange/importer/geonode_timeextent_handler.py, exchange/static/osgeo_importer/importer.js
```geonode_timeextent_handler``` will currently fail because osgeo importer does not set the layer name correctly on raster layers.
This will skip the time extent check on raster layers so publishing doesn't return an error to the user;
The warning about possible duplicate layers is shown even when a layer doesn't exist. Commenting out for now
=> Fix raster import error and don't warn about possible duplicate layers

exchange/templates/base/_resourcebase_snippet.html
It is desirable to be able to contact the publisher
of a piece of content, so that users can ask questions
of that user.
This gives a quick and convenient method to do so
on the page where users will most likely need that
information.
Currently this functionality misbehaves on the Explore
Layers page, and it's been suggested by Clarence that
we adjust that page to be a specialization of the search
page. That work will be covered in a future ticket.
=> Node 980 - Add link to publisher profile in Layer Search Card

exchange/static/css/django_classification_banner_overrides.css
Recently user notifications were changed to be a
new alert class. This change ensures that when the
classification banner is enabled that the alert
class is shifted down enough that it's not hidden
by the nav bar.
=> Fix issues with alerts/warnings being hidden

exchange/themes/templates/about.html
Addressing feedback: Adds a button to the about page under "What's New?" which will expand to show release notes (prior, all release notes were showing by default, which were sometimes long and stretched the page).
=> Make release notes expandable/collapsible

exchange/core/context_processors.py, exchange/settings/default.py, exchange/templates/search/_extent_filter.html
The extent filter uses a leaflet tile map in order
to filter results based on the contents shown
in the map. This map has to reach out across the
open internet in order to properly access the
tiles.
For some deploys this is not ideal, as it is
not possible to access the open internet due
to firewalls or other restrictions. As such it
was determined that simply disabling the filter
was the best way forward for those types of
networks.
=> Node-953 : Enable toggling the Extent Filter on Search Page

.travis.yml, docker/travis/Dockerfile.ci, docker/travis/pytests.sh, exchange/tests/celery_test.py, exchange/tests/csw_perms_test.py, exchange/tests/views_test.py
This replaces the Centos6 container we used for Travis with Centos7.
As part of the changes a couple of the test were fixed, which caused the increase in coverage.
=> Move travis to centos7

exchange/templates/base/_resourcebase_snippet.html, exchange/templates/layers/layer_detail.html
This fixes the OWS/OGC urls to point at the layer specific GetCapabilities.
Also removes the hard coded workspace, and instead either gets the workspace from the ```typename``` of from the resource's workspace attribute directly.
Added WMS and WCS for raster types.
The urls will now look like this:
https://exchange.boundlessgeo.io/geoserver/geonode/sfkjsdbf_e2f65ef5/ows?service=wms&version=1.3.0&request=GetCapabilities
https://exchange.boundlessgeo.io/geoserver/geonode/DEM/ows?request=GetCapabilities&service=WCS&version=2.0.1
https://exchange.boundlessgeo.io/geoserver/geonode/sfkjsdbf_e2f65ef5/ows?request=GetCapabilities&service=WFS&version=1.1.0
=> Correct OWS links for WMS/WFS/WCS

exchange/templates/maps/metadata_detail.html
The Map Metadata Detail Page was initially a copy
of the Layers Metadata Detail Page, and when it
was coppied over, the "Return to ..." Button wasn't
properly updated to use the Map's id, and would
return you to a blank layer search, instead of the
desired map.
Before:
After:
=> Fix Map Metadata Detail Page button

exchange/themes/templates/base.html, exchange/urls.py
**This PR enables the Retro Remote Services Workflow**
This PR in conjunction with the latest [WIP] commit on the 1.3.0/Geonode Branch provides better usability WRT registering remote services. The workflow includes support for ESRI REST and OGC WMS auto-population of initial metadata, extraction of underlying layers and exposes a distinct button to publish the metadata to Registry rather than doing it automatically upon save. We will phase out the existing /csw routes and the associated form.
=> Enable retro Remote Services workflow.

docker-compose.yml
Updates to docker-compose.yml file to work natively on Mac OS X.
Tested and works on Ubuntu 16.04, so the solution should have cross OS compatibility.
=> Mac docker file

exchange/storyscapes/templates/search/indexes/storyscapes/story_text.txt
When rebuilding the Exchange index, if storyscapes is enabled it will fail as this template does not exist. This will allow indices to be rebuilt correctly when storyscapes is enabled. This also should provide storyscapes title as a searchable field.
=> story_text.txt template added

exchange/templates/search/_general_filters.html, exchange/views.py
This PR hides facets that have a count equal to zero: Prior to this PR the filters would show all facets that have no match in the current search.
Example:
Choosing Map updates the list.
=> Hide facets with count equal to zero

docker/registry/Dockerfile
Registry Dockerfile sometimes outputs the following error when installing the packages listed inside the dockerfile:
Rpmdb checksum is invalid: dCDPT(pkg checksums): perl-version.x86_64 3:0.77-144.el6 - u
ERROR: Service 'registry' failed to build: The command '/bin/sh -c yum install -y python27 python27-devel python27-setuptools python27-virtualenv git' returned a non-zero code: 1
Moving the packages into one RUN statement alleviates this error.
=> Update Registry Dockerfile

exchange/settings/default.py
Part of https://github.com/GeoNode/django-osgeo-importer/pull/189
Adds a global setting to choose if rasters should be uploaded to geoserver, or used via EFS/NFS.
=> Add osgeo importer raster setting/attribute

exchange/static/js/search/workspace.html, exchange/themes/static/theme/css/site_base.css
Previously the length of the display for the name of
the item in the workspace was explicitly defined by
a number of characters. Because that section doesn't
use a monospace font, Layer names that had a collection
of wider characters like 'W' would take up more space
than Layers with names that had smaller letters like
'l'.
This change forces an explicit size for the display,
regardless of the size of the characters, causing
the names to trim at the proper length every time.
Additionally, you can now hover over a layer name
to see the full name, so if it is cut off and you
need to differentiate between two layers, you can.
Before:
After:
=> Fix workspace items sometimes displaying improperly

exchange/templates/base/_resourcebase_snippet.html
This corrects the map search template so that it links to the map correctly. Currently `id` refers to a uuid, not the django id. The URL wants the django id.
=> Use the django_id instead of id field for the map link

docker-compose.yml
Previously the worker container was added to the
external network, but not assigned an explicit IP.
This resulted in a race condition where it would
take the first available IP in the range (.2) which
in turn would cause the proxy container to fail to
start because its assigned IP was already taken by
the worker.
=> Fix race condition with worker container

README.rst, docker-compose.yml, docker/README.rst
Updates the root readme to point to the readme in the `docker` folder for local environment setup.   I also made some documentation updates in the docker readme that supersede #400 and #401
Additionally, I changed the port and removed the configuration exposing port 443 from the exchange container.  This fixes an issue that prevented the proxy container from starting.  Now you can access the Exchange UI through the proxy at http://localhost and https://localhost
=> updating readme & dev setup

exchange/importer/geonode_postimport_handler.py
The importer returns a path instead of a layer name on raster import, but changing to layer name would break raster import.
```GeoNodePostImportHandler``` will try different names, and if it still can't find a layer will return ```False``` to not break layer import
=> Fix raster import

exchange/themes/static/theme/css/site_base.css
Previously the "Set permissions" and "Create a
Map" buttons were designed in such a way that the
text would overflow the buttons and collide with
each other at certain page widths. This behavior
isn't desired, and the buttons were redesigned to
have a clean look and feel regardless of the page
width.
Relates to GeoNode PR: https://github.com/boundlessgeo/geonode/pull/95
=> Update workspace buttons layout and text

dev/run_tests.sh
Looks like at some point someone was trying to test something specific and accidentally committed it. Just moving the commented out part back to being what is run by our `run_tests` script so it has expected behaviour.
=> Fix test script to run all tests by default

exchange/themes/static/theme/css/site_base.css
Previously if you shrunk the browser window down
while on the homescreen the categories would
begin to overlap and become hard to read. This
behavior isn't desireable and leads to a poor user
experience.
=> Fix homepage category overlap issues

.env, exchange/settings/default.py, exchange/storyscapes/models/base.py, requirements.txt
Along with: https://github.com/boundlessgeo/geonode/pull/101
Fixes bugs introduced from: https://github.com/boundlessgeo/exchange/pull/468
Remaining issue: The app is not loading on startup for some reason. If I ssh into the instance and manually install the `requirements.txt` file, the elasticsearch app finally gets installed, and with a restart to the instance, everything works fine. Does anyone have any ideas why this could be? What logs should I be looking at? My exchange logs from building the instance: https://gist.github.com/travislbrundage/6dd081d281eae4d69b1bdd3303b1cc32
My requirements.txt file: https://gist.github.com/travislbrundage/66155b5d1121687a01037db2938b3fe4#file-gistfile1-txt-L9
Side note: I have to comment out these lines to get the instance to initially come up: …
=> Fixing bug with elasticsearch app

exchange/thumbnails/static/geonode/js/utils/thumbnail.js
Fixed calculation of thumbnail extents on Mac OS with retina.
Refs: BEX-537
=> Fix for thumbnails on retina displays
