- .gitmodules
- README.md
- exchange/templates/base.html
> added exchange-documentation as submodule

- exchange/templates/aggregator/base.html
- exchange/templates/site_base.html
This solves https://issues.boundlessgeo.com:8443/browse/NODE-246 but TODO: clean up all "webkit" instances in GeoNode/Exchange CSS
> make gradients cross-browser friendly

- exchange/settings/default.py
https://issues.boundlessgeo.com:8443/browse/NODE-145
> Added settings for a postgresgeogig database

- exchange/templates/base.html
For now, Exchange only supports English -- removing ability for users to change languages
> remove language switcher & support English only

- exchange/core/context_processors.py
- exchange/settings/default.py
- exchange/templates/base.html
Let e.g., JWICS Exchange instances specify a custom Boundless URL for footer link
> let boundless URL be set via settings

- exchange/core/context_processors.py
- exchange/settings/default.py
- exchange/templates/base.html
Followup on https://github.com/boundlessgeo/exchange/pull/30, per @BerryDaniel we also want to let the link text be explicitly set
> allow footer link text to be customized

- requirements.txt
It brings better error logging and fixes for harvesting GeoNetwork's
CSW. Services detected from GeoNetwork are now available in the admin
list.
> Registry 0.2.20

- requirements.txt
Added missing requirement to requirements.txt
> Added django-cache-url to requirements

- requirements.txt
Registry needs pycsw==2.1.dev for the CSW-T support.
> Reference latest pycsw commit for CSW-T enhancements.

- dev/bootstrap.sh
> trivial shell tidying in vagrant bootstrap script

- exchange/templates/services/service_register.html
> Minor text fix for adding a service

- exchange/core/context_processors.py
- exchange/core/models.py
- exchange/settings/cf.py
- exchange/settings/default.py
- exchange/urls.py
- exchange/version.py
- exchange/views.py
- exchange/wsgi.py
In order to allow the flake8 checks to pass in Travis CI, we need to make a few adjustments to existing code. This should at least be a down payment.
I'd like some help testing that this doesn't break anything I didn't think of testing.
> Fix current flake8 errors so Travis CI can start passing builds

- Vagrantfile
Dan and Glynnis found this to be necessary so everyone should have it instead of independently rediscovering the same problem and solution. 
Tracked in https://issues.boundlessgeo.com:8443/browse/NODE-434
> add a recommended workaround for Vagrant config

- .gitmodules
- README.md
removing documentation as a submodule. The docs will now be installed as a python package. A new pull request will be created for the changes.
> removed submodule of docs

- exchange/settings/default.py
- exchange/urls.py
- requirements.txt
The original was #18 and this can be closed if that gets resurrected. Creating this to contain discussion and show the code, which is currently broken due to all the merge conflicts between #18 and today.
> NODE-163: integrate osgeo importer (redux)

- exchange/settings/default.py
- requirements.txt
Addressing [[NODE-369]](https://issues.boundlessgeo.com:8443/browse/NODE-369)
> Load new documentation files

- docker/home/local_settings.py
The "registry removal" PR broke the docker dev environment.
> tweak ALLOWED_HOSTS so docker can work again

- .env
- Dockerfile
- docker-compose.yml
- docker/home/common.sh
Lets a docker based dev environment use a development version of MapLoom
> Added a break out for MapLoom

- docker/README.rst
Missed a char, MapLoom build instructions were garbled
> typo fix in dev docs

- docker/home/settings.sh
- exchange/core/models.py
- exchange/settings/default.py
- exchange/tasks.py
- exchange/templates/csw/new.html
- exchange/templates/csw/status.html
- exchange/templates/csw/status_fill.html
- exchange/urls.py
- exchange/views.py
Ref: NODE-506 & related subtasks.
This adds a user-facing form for creating new CSW Records in Registry. Form fields are based on preliminary CNP metadata fields (provided by @davisc ) and will likely be modified at a later date.
As this is an "MVP/demo" feature only at this point a direct link has not been added to the user menu. The form is available at `/csw/new` (i.e., 172.16.238.2/csw/new/ in dev); status page is at `/csw/status`.
**Screenshots:**
> Create UI to insert CSW Records

- exchange/settings/default.py
- exchange/templates/base/_resourcebase_snippet.html
- exchange/urls.py
- exchange/views.py
- requirements.txt
Adds unified search using GeoNode Haystack and Registry located on the same elasticsearch instance.
Requires HAYSTACK_SEARCH to be setup and set to True, ES_UNIFIED_SEARCH = True and ES_URL and REGISTRY_URL to be set.
> Unified Search

- docker/home/docker_oauth_apps.json
- exchange/settings/default.py
Resubmitting https://github.com/boundlessgeo/exchange/pull/134
> Add /o/token and /o/authorize to AUTH_EXEMPT_URLS 

- exchange/settings/default.py
- exchange/templates/layers/layer_detail.html
- requirements.txt
- Added `django_geonode_client` to exchange requirements
- Added `geonode-client` to the INSTALLED_APPS list
Refs:
NODE-682
> Added WebSDK Client to Layer and Map Preview.

- exchange/core/models.py
> Add 14 primary NGA categories of content as a drop down field

- exchange/static/js/search/workspace.html
- exchange/static/js/search/workspace.js
- exchange/templates/base/_resourcebase_snippet.html
- exchange/templates/search/search_scripts.html
> Turns the cart into a workspace and support registry layers

- exchange/core/fixtures/base_resources.json
- exchange/themes/templates/index.html
- exchange/views.py
Adds the 14 NGA Categories to base_resource.json setting the previous categories to is_choice=false. Modifies view and template for index.html to be driven by the fixtures rather than hard coded. See NODE-543
> add nga categories, make index.html use fixtures for categories

- .coveragerc
- .travis.yml
> send report to coveralls

- exchange/themes/templates/index.html
> Fixed index page to properly truncate chars for item title

- exchange/settings/_ldap.py
- exchange/settings/default.py
- requirements.txt
- migrated ldap config to a new settings file named _ldap
- added ability to support ldap and ad
- added the ability to map group searches to django roles is_active, is_staff, and is_superuser
- adjusted str2bool to handle None values
- bumped version of geonode to include changes to permissions
> Added Active Directory backend

- requirements.txt
Version now includes support for wgs84 bbox conversion when WGS84_MAP_CRS is set to True
Thanks @bartvde
> bump version of geonode-client

- requirements.txt
> Bump version do to whitelist requirement

- docker-compose.yml
replacing #153 due to a stale PR @stirringhalo
> Use local .env for configuration

- exchange/templates/base/_resourcebase_snippet.html
> Adds GeoGig Indicator to Search Card

- requirements.txt
Floating the geonode version while we're in development
> Float geonode version based on the exchange/1.2.0 branch

- exchange/themes/static/theme/css/site_base.css
- exchange/themes/templates/base.html
Per a request from @davisc, this PR updates the look and feel of the navigation to better match designs I recently implemented on MapStory. Included in this PR:
* Gradient background for navigation with solid color fallback for IE 9 and earlier
* Reordered so navigation links are grouped together and search bar is not in as close a proximity to them
* Moved all navigation links to the right side of the screen
* Changed caret icons and hover styles to match MapStory
* Decreased the height of the nav bar and made the logo size smaller so that it's sharper (and on a darker color so it's more legible)
All of these changes were addressed in style only, and no functionality has changed. As I discussed with @davisc, this PR *does not* cover improving the markup, user experience, or functionality …
> Update navbar appearance and reorder menu items

- exchange/templates/layers/layer_detail.html
Addresses [NODE-794](https://issues.boundlessgeo.com:8443/browse/NODE-794)
> Make info tab into a proper tab to be consistent with other UI elements

- exchange/settings/test_settings.py
Security finding for Use of Hard-coded Credentials for SECRET_KEY.
> adjust secret_key in test_settings.py

- requirements.txt
> use docs from github master

- MANIFEST.in
modified the MANIFEST.in to include the .gif file extension, which will package those file extensions now.
> add gif file type to be packaged also

- exchange/static/lib/viewer/site-theme.css
- exchange/storyscapes/templates/viewer/ol3-popup.js
- exchange/storyscapes/templates/viewer/story_detail.html
- exchange/storyscapes/templates/viewer/story_viewer.html
- exchange/storyscapes/templates/viewer/story_viewer.js
- exchange/storyscapes/templates/viewer/view_base.html
- exchange/storyscapes/templates/viewer/viewer_include.html
> adds the viewer page.

- exchange/auth/backends/auth0.py
- exchange/core/context_processors.py
- exchange/settings/default.py
- exchange/templates/account/login.html
- exchange/themes/static/theme/css/site_base.css
To configure:
export ENABLE_SOCIAL_LOGIN='True'
export OAUTH_AUTH0_KEY=''
export OAUTH_AUTH0_SECRET=''
export OAUTH_AUTH0_HOST='davisc.auth0.com'
export AUTH0_APP_NAME='My Application'
> Adds Auth0 support

- exchange/settings/default.py
Currently the majority of errors are not being logged, comment out our logging changes to make sure errors are mostly logged
> Comment out logging

- exchange/views.py
> use prefix for search words in unified search

- exchange/core/admin.py
- exchange/core/migrations/0003_auto_20170504_1443.py
- exchange/core/models.py
- exchange/tests/celery_test.py
- exchange/thumbnails/migrations/0002_auto_20170504_1443.py
- The first entry in the CSW Insert form is for the source field
- The "Source" entry is relabeled "Service Endpoint URL"
- The "Creator" entry is replaced with "Agency"
- Remove "Contact" entry
- Remove "Relation" entry
- Add "Email" entry
- Add "Phone" entry
> Node 884 - Improve CSW form

- exchange/views.py
Added the "has_time" facet which is available with this GeoNode PR:
- https://github.com/boundlessgeo/geonode/pull/56
> Added support for the has_time facet in exchange.

- exchange/themes/static/theme/css/site_base.css
- exchange/themes/templates/index.html
- use item.detail for thumbnail url for all types
- resize thumbnail to correct size
> featured thumbnail fix

- exchange/core/forms.py
- exchange/core/migrations/0004_cswrecordreference.py
- exchange/core/models.py
- exchange/static/js/formset/jquery.formset.js
- exchange/tasks.py
- exchange/templates/csw/new.html
- exchange/templates/csw/record_list.html
- exchange/themes/templates/base.html
- exchange/urls.py
- exchange/views.py
The next version of registry will inspect the references in order to determine whether a thumbnail can be generated. This PR honors current and future functionality.
**Adds paging to the list view**
**Autocompletes supported services**
**Lists the Service References**
**Friendly Message when manual entry is required**
> Improvements to registry workflow and includes references support

- exchange/templates/csw/new.html
> Fixed spelling

- exchange/views.py
> Set version correctly when no commit hash exist

- exchange/themes/templates/base.html
- exchange/themes/templates/index.html
Changes in this PR:
- A map in featured content will now open the map itself, instead of the map page.
- A layer in featured content will now open the layer in a new map, instead of the layer page
- Allow the register button to show when registration is enabled
> Featured content improvements 

- exchange/views.py
> Applies css class to form fields

- exchange/views.py
https://github.com/boundlessgeo/exchange/blob/master/exchange/storyscapes/search_indexes.py#L76
> Allow stories to be returned as results.

- exchange/templates/layers/metadata_detail.html
- exchange/templates/maps/metadata_detail.html
> Fixed spelling error

- exchange/static/bower.json
- exchange/static/js/search/search.js
- exchange/static/osgeo_importer/importer.js
- exchange/themes/templates/index.html
Only remaining error that I can see:
Promise handling seems to be the only change which needed to be addressed.
Coincides with: https://github.com/boundlessgeo/geonode/pull/70
> Adjust promise resolution with bump to angular 1.6.5

- exchange/templates/base/_resourcebase_snippet.html
Link to WMS of uploaded GeoNode layer should copy specific reference
> Update quick copy link

- exchange/core/admin.py
- exchange/core/forms.py
- exchange/core/migrations/0007_auto_20170809_1750.py
- exchange/core/migrations/0008_adds_content_manager_group.py
- exchange/core/models.py
- exchange/tasks.py
- exchange/themes/templates/base.html
- exchange/urls.py
- exchange/views.py
Fixed bug where Registry categories missing the & after being registered.
`
>>> from exchange.tasks import create_new_csw
>>> create_new_csw('b46b06d7-227b-4266-9924-43fb0f6655ea')
<csw:Transaction xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
xmlns:ows="http://www.opengis.net/ows"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2
http://schemas.opengis.net/csw/3.0.0/CSW-publication.xsd"
service="CSW" version="2.0.2"
xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:dct="http://purl.org/dc/terms/"
xmlns:registry="http://gis.harvard.edu/HHypermap/registry/0.1" >
<csw:Insert>
<csw:Record xmlns:registry="http://gis.harvard.edu/HHypermap/registry/0.1">
<dc:identifier>b46b06d7-227b-4266-9924-43fb0f6655ea</dc:identifier> …
> Fixed bug where Registry categories were missing

- exchange/templates/people/profile_detail.html
> replace missing images with group avatar

- docker/README.rst
> Improved install docs for MapLoom section

- exchange/static/js/search/search.js
Makes sure that the click listeners for facets are tied to the "a" element.
> fix for node1164

- exchange/tests/views_test.py
Unit test for the layer_publish view which was recently added: https://github.com/boundlessgeo/exchange/pull/374/files#diff-0f1f903cd2c95beaee07a5f4720a4821R137
> Add unit test for layer_publish

- docker/registry/registry_mappings_overrides.json
- exchange/core/migrations/0008_adds_content_manager_group.py
- exchange/tasks.py
- exchange/templates/services/service_register.html
- exchange/themes/templates/base.html
- exchange/views.py
Remote Service functionality is only available to members of the csw_manager group.
> swap the perms to the service model

- exchange/views.py
Coincides with: https://github.com/boundlessgeo/geonode/pull/85
> Change query to django_id to reflect changes with elasticsearch

- exchange/themes/templates/base.html
Re-arranges menu to fix BEX-360 (feedback from SEs)
> Re-arranges data menu (BEX-360)

- exchange/templates/base/_resourcebase_snippet.html
> Thumbnail link fix for layers

- exchange/static/osgeo_importer/importer.js
- exchange/static/osgeo_importer/partials/uploadWizard.html
depends on https://github.com/boundlessgeo/geonode/pull/96
> Expose option to set permissions on the layer.

- exchange/static/js/search/search.js
- exchange/templates/base/_resourcebase_snippet.html
Fixed:
- Link not associated with the title of the card
- The layer data type should say FeatureService
- The MapServer link is not showing up
> BEX-502 fixed card display

- exchange/templates/services/service_register.html
This PR updates the error messages and handles the long poll for the asynchronous registration task. The PR depends on the corresponding Geonode PR for enabling the WebServiceRegistrationJob celery task.
> update error messages and support long poll

- exchange/templates/services/service_register.html
This PR updates the error messages and handles the long poll for the asynchronous registration task. The PR depends on the corresponding Geonode PR for enabling the WebServiceRegistrationJob celery task.
> Bex 281 - update error messages and support long poll

- exchange/core/migrations/0008_adds_content_manager_group.py
- exchange/tasks.py
- exchange/templates/services/service_register.html
This PR fixes:
1) Typo in the error message
2) Handles the condition where no layers are returned from remote service registration
3) Set the user defined name for the service rather than the name extracted from the service.
4) Uncomments the migration for csw_manager
> Fixed typo in error message.

- Jenkinsfile
- docker/devops/helper.sh
add exit code if healthcheck fails
> add healthcheck for exchange in pipeline

- .github/CODEOWNERS
https://github.com/blog/2392-introducing-code-owners
> Adding exchange qa members to auto review as code owners in github

- Makefile
- docker/devops/bex-py27-stretch/Dockerfile
* BEX-561
Create Makefile for easy run of commands
```
hostname$ make
make lint     - run to lint (style check) repo
make html     - build sphinx documentation
make start    - start containers
make stop     - stop containers
make purge    - stop containers and prune volumes
make recreate - stop containers, prune volumes and recreate/build containers
make test     - run unit tests
```
> BEX-561 (#511)

- .github/CODEOWNERS
- .gitignore
- Dockerfile
- docker-compose.yml
- docker/README.md
- docker/exchange/django.sh
- docker/exchange/entrypoint.sh
- docker/exchange/supervisor.conf
- docker/nginx/nginx.conf
- requirements.txt
- run celery and django using supervisord
- set log output for supervisord to stdout
- add startup env check for DEV=True, if set then django runserver is used, else waitress with DEBUG=False
- updated README
> Combine worker and exchange container

- .gitignore
- Dockerfile
- Makefile
- docker-compose.yml
- docker/README.md
- docker/devops/bex-py27-stretch/Dockerfile
- docker/exchange/django.sh
- docker/exchange/entrypoint.sh
- docker/exchange/supervisor.conf
- docker/nginx/nginx.conf
- requirements.txt
This adds the 2 additions that were made to the dev env for 1.3.x
- including a makefile for easy setup/starting/linting...etc
- consolidation of worker and exchange images using supervisord
- updated readme
> Combine django celery master

- docs/maps/index.rst
Made a note that the time slider does not work when an enabled layer is added via maploom.
> Time slider issues

- exchange/thumbnails/static/geonode/js/utils/thumbnail.js
Fix for thumbnails on retina displays BEX-537
> Cherry Pick Changes From PR #515

- exchange/search/views.py
Fixes a regression where users could search for objects they may not have access to.
_Add detailed steps for testing/review team to verify._
1. Cleanup previous state
```bash
make purge
```
2. Checkout PR
__Using git command (command line interface)__
```bash
pr_id=ADD_PR_NUMBER_HERE
git checkout master
git branch -D $pr_id
git fetch
git fetch origin pull/$pr_id/head:$pr_id
git checkout $pr_id
git submodule init
git submodule update --remote --recursive
```
__Using [Gitkraken](https://www.gitkraken.com/)__
+ In GitKraken, right click on the pull request you want to review. Select Add Remote and Checkout (the PR).
3. Start exchange
```bash
make start
```
4. Exchange Healthcheck
```bash
docker inspect --format '{{ .State.Health.Status }}' exchange
```
__NOTE:__ Only continue the following …
> filter search results by allowed access

- exchange/thumbnails/tasks.py
NA
This attempts to ensure thumbnails are more likely to get generated for WMS remote services.
Auto thumbnail generation for these services should now work:
```
https://demo.geo-solutions.it/geoserver/ows	
https://nowcoast.noaa.gov/arcgis/services/nowcoast/analysis_meteohydro_sfc_qpe_time/MapServer/WMSServer
https://maps2.dcgis.dc.gov/dcgis/services/DCGIS_DATA/Environment_WebMercator/MapServer/WMSServer	
```
_Add detailed steps for testing/review team to verify._
1. Cleanup previous state
```bash
make purge
```
2. Checkout PR
__Using git command (command line interface)__
```bash
pr_id=ADD_PR_NUMBER_HERE
git checkout master
git branch -D $pr_id
git fetch
git fetch origin pull/$pr_id/head:$pr_id
git checkout $pr_id
git submodule init
git submodule update --remote --recursive
```
__Using …
> Remote services auto thumb generation fix 
